---
name: Adam Shand
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: BSc(Hons), BMarSc
position: Environmental Data Analyst
address: Townsville, Australia
email: adamshand22@gmail.com
www: adamshand22.com
github: add-am
headcolor: "414141"
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
#install.packages("vitae")
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Employment

```{r employment}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Environmental Data Analyst", "Healthy Waters Partnership for the Dry Tropics (HWPDT)", "Townsville, Australia", "Apr. 2022 - Present", 
    list("Collaborated with industry, government, NGOs, and community stakeholders to deliver environmental monitoring reports.",
         "Implemented the ANZECC (2000) and Environmental Protection Policy water quality guidelines for a range of monitoring projects.",
         "Analysed multiple environmental indicators including climate data, water quality data, vegetation surveys, and fauna surveys.",
         "Developed automated workflows for tasks such as data cleaning, manipulation, analysis, and visualisation.",
         "Worked extensively with spatial data (rasters, vectors), flat files (spreadsheets, Excel), and 3-dimensional data (topography, hypercubes).",
         "Engaged in public outreach and communication by delivering presentations at events, lecturing at JCU, and running stalls at community days.",
         "Extensively used a range of technical programs including Python, R, SQL, Tableau, QGIS, ArcGIS, and the Microsoft suite."),
  "Research Assistant", "Griffith University", "Gold Coast, Australia", "Nov. 2018 - Jan 2022", 
    list("Developed and applied tools for monitoring and resource assessment in marine and estuarine environments.",
         "Utilised advanced data analysis, data management, coding, and automation techniques for multiple scientific publications.",
         "Designed and presented complex technical and scientific reports to collaborators and stakeholders.",
         "Served as a project manager for multiple desktop and in-field studies.",
         "Supervised and provided guidance to a team of 7 undergradutate students and interns.")) %>% 
  detailed_entries(role, dates, company, loc, details)
```

# Education and Awards

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "BSc (Hons) in Marine Science", "Griffith University", "Gold Coast, Australia", "Feb. 2020 - Nov. 2020", 
    list("Recipient of the Academic Excellence Award (2020).",
         "First Class Honours with Distinction (GPA 7.0/7.0).",
         "Honours research project was to develop an automated image recognition and indentification system for estuarine fish species.",
         "Studied units including Scientific Data Analysis, Scientific Report Writing, and Research Planning"),
  "BMarSc in Marine Ecology", "Griffith University", "Gold Coast, Australia", "Feb. 2017 - Nov. 2019", 
    list("Recipient of the Academic Excellence Award (2017, 2018, 2019).",
         "Graduate with Distinction (GPA 6.5/7.0).",
         "Mentor for the Griffith University Science Stream (2019).",
         "Capstone project was to assess the impact of soft coral allelopathy on surrounding hard coral cover.",
         "Studied units including Applied Data Science, Environmental Chemistry, Ecotoxicology, and Estuarine Ecology.")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```


# Qualifications

```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Fire Extinguisher Training", "Port of Townsville", "2025",
  "Carbon Literacy Standard", "ThinkZero", "2024",
  "HLTAID011 - Provide First Aid", "ABC First Aid", "2023",
  "HLTAID010 - PRovide basic emergency life support", "ABC First Aid", "2023",
  "HLTAID009 - Provide cardiopulmonary resuscitation", "ABC First Aid", "2023",
  "Aquatic Environment Monitoring Skills", "JCU, TropWater", "2023",
  "Drone Pilot (RPA Operator Accreditation)", "CASA", "2023",
  "Lifetime Member of the Golden Key International Honour Society", "Griffith University", "2018",
  "Recreational Boat License", "DTMR, QLD", "2017",
  "Advanced Open Water Diver", "PADI", "2016",
  "Certificate I in Maritime Operations (MAR10313)", "TAFE, NSW", "2015",
  "Class C and Class RE Manual Drivers License", "DTMR, QLD", "2015"
) %>%
  brief_entries(award, year, from)
```
